apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: demoapp-namespace
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: my-ci-cd-app